const environment = process.env.REACT_ENV;

let EES_BASE_URL;
let REGISTRATION_SERVICE_BASE_URL;
let RECAPTCHA_KEY;
let DEFAULT_WS_NODE;
let WS_NODE_LIST_URL_NODE1;
let WS_NODE_LIST_URL_NODE2;
let WS_NODE_LIST_URL_NODE3;

if (environment === 'develop') {
    EES_BASE_URL = process.env.REACT_APP_EES_BASE_URL_DEV;
    REGISTRATION_SERVICE_BASE_URL = process.env.REACT_APP_REGISTRATION_SERVICE_BASE_URL_DEV;
    RECAPTCHA_KEY = process.env.REACT_APP_RECAPTCHA_KEY_DEV;
    DEFAULT_WS_NODE = process.env.REACT_APP_DEFAULT_WS_NODE_DEV;
    WS_NODE_LIST_URL_NODE1 = process.env.REACT_WS_NODE_LIST_URL_NODE1_DEV;
    WS_NODE_LIST_URL_NODE2 = process.env.REACT_WS_NODE_LIST_URL_NODE2_DEV;
    WS_NODE_LIST_URL_NODE3 = process.env.REACT_WS_NODE_LIST_URL_NODE3_DEV;
}
else if (environment === 'prod') {
    EES_BASE_URL = process.env.REACT_APP_EES_BASE_URL;
    REGISTRATION_SERVICE_BASE_URL = process.env.REACT_APP_REGISTRATION_SERVICE_BASE_URL;
    RECAPTCHA_KEY = process.env.REACT_APP_RECAPTCHA_KEY;
    DEFAULT_WS_NODE = process.env.REACT_APP_DEFAULT_WS_NODE;
    WS_NODE_LIST_URL_NODE1 = process.env.REACT_WS_NODE_LIST_URL_NODE1;
    WS_NODE_LIST_URL_NODE2 = process.env.REACT_WS_NODE_LIST_URL_NODE2;
    WS_NODE_LIST_URL_NODE3 = process.env.REACT_WS_NODE_LIST_URL_NODE3;
}

export { 
    EES_BASE_URL,
    REGISTRATION_SERVICE_BASE_URL,
    RECAPTCHA_KEY,
    DEFAULT_WS_NODE,
    WS_NODE_LIST_URL_NODE1,
    WS_NODE_LIST_URL_NODE2,
    WS_NODE_LIST_URL_NODE3
};